import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedHomeProduct {
  final List<HomeProductModel> results;

  AutogeneratedHomeProduct({this.results});

  factory AutogeneratedHomeProduct.fromJson(Map<String, dynamic> json) {
    List<HomeProductModel> temp;
    if (json['results'] != null) {
      temp = <HomeProductModel>[];
      json['results'].forEach((v) {
        temp.add(HomeProductModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedHomeProduct(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class HomeProductModel extends Equatable {
  final int id;
  final String name;

  HomeProductModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory HomeProductModel.fromJson(Map<String, dynamic> json) {
    return HomeProductModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
