import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedHomeSlider {
  final List<HomeSliderModel> results;

  AutogeneratedHomeSlider({this.results});

  factory AutogeneratedHomeSlider.fromJson(Map<String, dynamic> json) {
    List<HomeSliderModel> temp;
    if (json['results'] != null) {
      temp = <HomeSliderModel>[];
      json['results'].forEach((v) {
        temp.add(HomeSliderModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedHomeSlider(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class HomeSliderModel extends Equatable {
  final int id;
  final String name;

  HomeSliderModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory HomeSliderModel.fromJson(Map<String, dynamic> json) {
    return HomeSliderModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
