import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedSearch {
  final List<SearchModel> results;

  AutogeneratedSearch({this.results});

  factory AutogeneratedSearch.fromJson(Map<String, dynamic> json) {
    List<SearchModel> temp;
    if (json['results'] != null) {
      temp = <SearchModel>[];
      json['results'].forEach((v) {
        temp.add(SearchModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedSearch(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SearchModel extends Equatable {
  final int id;
  final String name;

  SearchModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory SearchModel.fromJson(Map<String, dynamic> json) {
    return SearchModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
