import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedArchive {
  final List<ArchiveModel> results;

  AutogeneratedArchive({this.results});

  factory AutogeneratedArchive.fromJson(Map<String, dynamic> json) {
    List<ArchiveModel> temp;
    if (json['results'] != null) {
      temp = <ArchiveModel>[];
      json['results'].forEach((v) {
        temp.add(ArchiveModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedArchive(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ArchiveModel extends Equatable {
  final int id;
  final String name;

  ArchiveModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory ArchiveModel.fromJson(Map<String, dynamic> json) {
    return ArchiveModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
