import 'package:equatable/equatable.dart';

class AutogeneratedCategory {
  final List<CategoryModel> results;

  AutogeneratedCategory({this.results});

  factory AutogeneratedCategory.fromJson(Map<String, dynamic> json) {
    List<CategoryModel> temp;
    if (json['results'] != null) {
      temp = <CategoryModel>[];
      json['results'].forEach((v) {
        temp.add(CategoryModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedCategory(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class CategoryModel extends Equatable {
  final int id;
  final String name;

  CategoryModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory CategoryModel.fromJson(Map<String, dynamic> json) {
    return CategoryModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}
